/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./politica-de-privacidade.html",
    "./bairros/**/*.html",
    "./servicos/**/*.html",
    "./atendimento-na-zona-oeste/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#dfe3e9",
        "on-error": "#ffffff",
        "on-background": "#171c21",
        "on-secondary-fixed-variant": "#693c00",
        "on-primary-fixed": "#0d1d27",
        "tertiary-fixed-dim": "#3de273",
        "on-primary-fixed-variant": "#394953",
        "on-primary": "#ffffff",
        "primary-container": "#c9dae7",
        "surface-dim": "#d6dae1",
        "tertiary": "#006d2f",
        "tertiary-container": "#53f482",
        "tertiary-fixed": "#66ff8e",
        "outline": "#73777b",
        "primary": "#50606c",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#643900",
        "surface-container": "#eaeef5",
        "on-surface-variant": "#43474b",
        "inverse-primary": "#b8c9d6",
        "on-secondary-fixed": "#2c1600",
        "inverse-on-surface": "#edf1f7",
        "on-surface": "#171c21",
        "surface-bright": "#f6f9ff",
        "secondary": "#8a5100",
        "on-tertiary-fixed": "#002109",
        "surface-container-highest": "#dfe3e9",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b8c9d6",
        "background": "#f6f9ff",
        "inverse-surface": "#2c3136",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdcbd",
        "on-primary-container": "#50606b",
        "primary-fixed": "#d4e5f2",
        "surface-container-low": "#f0f4fa",
        "surface": "#f6f9ff",
        "on-tertiary-fixed-variant": "#005322",
        "outline-variant": "#c3c7cb",
        "surface-container-high": "#e4e8ef",
        "on-tertiary-container": "#006c2f",
        "secondary-fixed-dim": "#ffb86f",
        "secondary-container": "#fe9800",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#50606c",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        body: ["Manrope", "system-ui", "sans-serif"],
        label: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
